### PR TITLE
Use grids to render stats

### PR DESCRIPTION
**Pull request by spenserblack**
Resizes TUI elements relative to terminal size.

Addresses #8

This *does* make some changes to the ratio of the element sizes within the UI, so it won't be a 1:1 match to the previous UI. The most noticeable change is that the TUI now takes up *all of the height* in the terminal. Let me know if there should be a maximum height/width set instead of always being "fullscreen".

### CODE REVIEW

**Review by irevenko — APPROVED** [review]

**Review by irevenko — APPROVED** [review]

**Review by irevenko — APPROVED** [review]

**Comment by irevenko** [comment]
sorry for late review and thanks for helping

**Comment by irevenko** [comment]
it is a little bit broken on windows havent checked on linux so need to fix
image

**Comment by irevenko** [comment]
So forks and stars per lang are shorter than they need to be 
Avatar is too wide

**Comment by irevenko** [comment]
old look
image

**Comment by irevenko** [comment]
i reverted the commit

**Comment by spenserblack** [comment]
>i reverted the commit

I'm surprised GitHub still thinks it's merged :laughing:

>Avatar is too wide

Should be fixed by making sure its ratio is a square. Should be helped by enforcing a certain width/height ratio for the whole TUI. I should have tested on a wider screen -- I only checked on a vertical screen :facepalm:

>So forks and stars per lang are shorter than they need to be

I'm not really sure what you mean, since forks per lang is shorter in the old version than in your screenshot of the new version. Anyway, this should be fixable by
- Enforcing a height/width ratio for the TUI
- Adjusting grid rows/columns for more preferable ratios

***

EDIT:
>>So forks and stars per lang are shorter than they need to be

>I'm not really sure what you mean

Oh, perhaps you were referring to width? I interpreted "shorter" as referring to height.

**Pull request merged**
